### ISSUE TITLE
Error-Message "Something went wrong. Please try it again. Photobooth reloads automatically..."

### ISSUE THREAD

**Issue by FUF1** [PhotoboothProject/PhotoboothProject.github.io#1]
When taking a picture the shutter of the DSLR clicks, but photobooth shows the message "Something went wrong. Please try it again. Photobooth reloads automatically..." and no picture.
The admin interface, the front end, it all works as expected. Only the not showing picture and the error message is the issue.
Taking a Picture with gphoto2 and the DSLR via CLI works. It also does not work when a Pi-Camera is attached and the "Take picture" command is modified according to the FAQ.

I used the automated installation guide provided in the install section.
Thanks for your help and for the development of the software.

**Comment by FUF1** [comment]
Actually, I now was able to resolve the issue. Altough my current OS is bullseye, the suggested FAQ-command for the Raspberry Pi-Camera for bullseye does not work (see error message above) but the one for buster ("raspistill -n -o %s -q 100 -t 1 | echo Done") does.
And the DSLR now works too. The problem was, that RAW+JPEG was setup as an option in the camera menu. When it is switched to only JPEG it works. Maybe that should go into the FAQ as well. Thanks for this awesome software! (Maybe it would be a good idea to officially archive the old repos and just keep the current one open to avoid confusion.)

**Comment by andi34** [comment]
@FUF1 thanks for the suggestion. My a old fork is archived (https://github.com/andi34/photobooth) , but I won't decide this for the origial repo at https://github.com/andreknieriem/photobooth , this should be discussed with André.

`raspistill` only works on bullseye if the legacy camera Interface is enabled, else the command mentioned inside the FAQ `libcamerastill` is right.

Gphoto2 issues are most of the time camera specific, but I'll think about adding some general Information. I've written some general things down In German already which I would need to translate.
