### ISSUE TITLE
cameracontrol.py doesnt work. (Livepreview & Picture Capture)

### ISSUE THREAD

**Issue by RauIonkraft** [PhotoboothProject/PhotoboothProject.github.io#2]
![grafik](https://user-images.githubusercontent.com/90255029/210849628-f71715df-67d0-4f9d-a7d7-fc614f3a5569.png)
**Describe the bug**
Also LiveVorschau geht, mit gphoto können auch bilder aufgenommen werden nur mit cameracontrol py klappt es nicht. ist eine Alpha 5100

LiveView ist working proper, but no picture can be taken.

pi@raspberrypi:/var/www/html/api $ sudo -u www-data python3 cameracontrol.py --capture-image-and-download test.jpg
Connected to camera
Capturing image
An error occured: [-2] Bad parameters

**Expected behavior**

Capture Image with cameracontrol.py

**Photobooth Version**

4.x
**Browser and browser version**

No response
**Operating System**

Raspberry PI OS
**Did it work before?**

No first try
Latest working version

No response
**Additional context**

No response

**Comment by andi34** [comment]
Right place at https://github.com/PhotoboothProject/photobooth/issues/119
